Power Ups - phase 1
yorkpirates/Assessment-2-Game pull request #26
Opened 2022-03-11 10:06 UTC by RumiaTouhou

2022-03-11 10:13 UTC, printincident commented on core/src/com/mygdx/game/PirateGame.java
> -import com.mygdx.game.UI.*;
Put this line back as we just want to import everything

2022-03-11 10:16 UTC, ameliarwig commented on core/src/com/mygdx/game/Components/Pirate.java
> -    public static int plunder;
why no more static?

2022-03-11 10:17 UTC, ameliarwig commented on core/src/com/mygdx/game/PirateGame.java
> +import javax.annotation                                                                                                                                                        .Resource;
??? red ting

2022-03-11 10:27 UTC, printincident requested changes

2022-03-11 10:27 UTC, printincident commented on core/src/com/mygdx/game/PirateGame.java
> +import javax.annotation                                                                                                                                                        .Resource;
I don't even know what this is

2022-03-11 10:27 UTC, printincident commented on core/src/META-INF/MANIFEST.MF
> +Manifest-Version: 1.0
Why is there a new Manifest

2022-03-11 10:27 UTC, printincident commented on core/src/com/mygdx/game/Components/Pirate.java
> +    private boolean isImmortality;
Could this not be managed by a object

2022-03-11 10:27 UTC, printincident commented on core/src/com/mygdx/game/Entitys/TimeBar.java
> + * @author Rrryaan
Where did this come from

2022-03-11 10:36 UTC, printincident commented on core/src/com/mygdx/game/PirateGame.java
> +import javax.annotation                                                                                                                                                        .Resource;
does this even compile??

2022-03-11 10:38 UTC, printincident commented on core/src/com/mygdx/game/PirateGame.java
> +import javax.annotation                                                                                                                                                        .Resource;
it doesn't

2022-03-28 15:34 UTC, dom-hall commented
There are a lot of changes to existing code and deleted work by other team members. This is being resolved in PR #33.

2022-03-28 15:34 UTC, closed without merging